on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - name: install dependencies
        run: |
          pipenv install -r web-app/requirements.txt
      - name: run tests
        run: |
          pipenv install pytest
      run: pipenv run pytest web-app/test_app.py